# This is a basic workflow to help you get started with Actions

name: bruno cli CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_bruno_api_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm install -g @usebruno/cli
    - name: run tests
      run: bru run --env restfull
